### ISSUE TITLE
Fails to typecheck paper's example

### ISSUE THREAD

**Issue by abailly** [abailly/xxi-century-typed#1]
I am currently facing a really strange issue: An example from the paper fails to typecheck properly with any implementation I have found so far. 

With my implementation (this project), trying to typecheck the following declarations

```
Bool : U = Sum (true | false);
elimBool : Π C : Bool → U . C $false → C $true → Π b : Bool . C b  = λ C . λ h0 . λ h1 . fun (true → h1 | false → h0);
```

yields the following error:

```
[4] expr Var "h1" does not have type (#0 $true #3), inferred type is (#0 $true ()), failed to equate normalization (#0 ($true #3)) with (#0 $true) in env {_ ↦ #3, h1 ↦ #2, h0 ↦ #1, C ↦ #0, Bool : U ↦ Sum(true| false), Bool : U ↦ Sum(true| false), ∅} and context {h1 ↦ (#0 $true ()), h0 ↦ (#0 $false ()), C ↦ Π Sum(true| false, {Bool : U ↦ Sum(true| false), ∅}) . <λ _ . U , {Bool : U ↦ Sum(true| false), Bool : U ↦ Sum(true| false), ∅}>, Bool ↦ U, Bool ↦ U, ∅}
```

MiniTT's type-checker is based on _normalization_ of _values_: Type-checker evaluates expressions appearing in types and when it needs to typecheck a symbol (or a pattern) it ensures that the normalisation of the resolved value and of the inferred one are equal. This is nice because it means "unification" boils down to syntactic equality of terms. 

But this fails on such a simple example and it also fails on the simpler `Unit` type with `elimUnit` rule.

Using the aforementioned [Mini-TT](https://github.com/kino3/Mini-TT) implementation with the following expression:

``` 
let Bool : U = Sum (true 1 | false 1) ;
let elimBool : Pi C : Bool -> U . C ($false 0) -> C ($true 0) -> Pi b : Bool . C b  = \  C . \  h0 . \ h1 . fun (true -> \ x . h1 | false -> \ x . h0) ;
0
```

which is equivalent to ours but for slight syntactic discrepancies yields the following error:

```
checking let Bool : U = foo (true 1 | false 1)
checking let elimBool : Pi C : Pi _ : Bool . U . Pi _ : C ($ false 0). Pi _ : C ($ true 0). Pi b : Bool . C b = \ C . \ h0 . \ h1 . foo (true -> \ _ . h1 | false -> \ _ . h0)
*** Exception: eqNf: TC#0 ($ true TC#3)=/=TC#0 ($ true 0)
```

I am puzzled...

**Comment by bobatkey** [comment]
(I saw your post on the Idris mailing list)

As far as I can tell, the problem is that the type checkers are both correct in the sense that they are implementing the typing rules in the Mini-TT paper, but that example won't type check with those rules (at least as given). I think there is a bug in that example in the paper.

The error message you are getting in both cases is complaining that the types `C (true x)` and `C (true 0)` are not equal, where `x` has type `1`. The type checker does not "know" that the only value of type `1` is `0`, which would allow it to deduce that the types are equal. I think this problem makes the Mini-TT system almost unusable -- there is no way to write eliminators for data types with nullary constructors!

You have three options:

 1. Change the equality check to recognise when terms of type `1` are being compared, and just assume they are always equal. This essentially adds a new rule to the system: eta for unit types. Given your currently implementation, this is a fairly major change. You'll need to keep track of type information during the readback phase.

 2. Allow data constructors to take no arguments. This avoids the problem of knowing that all values of type `1` are `0` by not needing a unit argument for nullary data constructors.

 3. Include an additional eliminator construct for eliminating values of unit type. This would essentially be an "induction" rule for `1` that states propositionally that all elements of `1` are `0`. However, it would need to be explicitly invoked by the user, instead of being automatic as in option (1).

**Comment by abailly** [comment]
Thanks a lot @bobatkey for detailed suggestions and taking the time to go through this minor puzzle. I initially thought about 1. as it seems definitely obvious the only possible value for `1` is `0` and a normalized variable should always considered equal to a constant `0`. However as you noticed the `readback` function is purely structural and carries no knowledge about the types of the objects it manipulates. It is not that involved to add the typing `Context` to `Normalize` but that won't really help as the types are attached to `Expr`essions and not to normalized ones and the type of `#3` (the neutral variable) is not known, even though it could be inferred. I was really thinking of doing something adhoc like noticing `#3` is actually bound to `_` and hence can be equated to any value but that sounds a bit clunky.

Option 2. seems both simpler and consistent with common practice, so I will probably go down that route although there might be other subtle issues lurking ahead.

What's bugging me slightly is that 1/ I wrote to one of the original author of the paper without much success and 2/ this is supposedly a research paper and there's even an implementation provided. If the type system does not work, as it seems quite certain now, it is somewhat shocking nobody noticed it. Am I being naive? 

Anyhow, thanks again for your very helpful comment.

**Comment by bobatkey** [comment]
If it helps, I can recommend the paper "[A tutorial implementation of a dependently typed lambda calculus](https://www.andres-loeh.de/LambdaPi/LambdaPi.pdf)" by Löh, McBride and Swierstra as a solid introduction to implementing dependent types -- it is the source I used to learn. The example code is, in my opinion, much easier to read than the Mini-TT paper, and is interleaved with the description of the type system, which makes it easier to see what is going on.

**Comment by abailly** [comment]
It does ! 👍
